# Generated by Django 5.0.6 on 2024-06-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('platform', models.CharField(max_length=20)),
                ('status', models.CharField(default='scheduled', max_length=20)),
            ],
        ),
    ]
